"""Registry of strict manuscript value tokens."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class TokenSpec:
    """Manuscript variable token with strict source-guard semantics."""

    name: str
    strict_value: bool = True


_TOKEN_SPECS: tuple[TokenSpec, ...] = tuple(
    TokenSpec(name)
    for name in """
    ACCEPTED_CANDIDATE_ID ACCEPTED_CANDIDATE_STATUS ACCEPTED_CANDIDATE_TITLE ACCEPTED_MODEL_TYPE
    ACCEPTED_MODEL_TYPE_LABEL ACCEPTED_PARAMETER_COUNT ACCURACY_DELTA ACCEPTED_ACCURACY_INTERVAL
    ACCEPTED_CALIBRATION_ECE ACCEPTED_MACRO_F1 BOOTSTRAP_ACCURACY_INTERVAL BOOTSTRAP_MACRO_F1_INTERVAL
    AUTONOMY_LEVEL BASELINE_ACCURACY BASELINE_ID BASELINE_MODEL_TYPE BASELINE_MODEL_TYPE_LABEL BENCHMARK_SCORE
    BEST_ACCURACY BUDGET_EXHAUSTED CANDIDATE_BUDGET CANDIDATE_COUNT DATASET_NAME DATASET_CLASS_COUNT
    DATASET_IMAGE_SHAPE DATASET_SHORT_NAME DATASET_SOURCE DISCLOSURE_TEXT EVALUATED_CANDIDATE_COUNT
    DEFERRED_CANDIDATE_COUNT IMAGE_SHAPE METRIC_DIRECTION METRIC_NAME ML_TASK_NAME MODEL_FAMILY_LABELS
    REVIEW_POLICY TEST_SIZE TRAIN_SIZE TRAIN_PER_CLASS_COUNT TEST_PER_CLASS_COUNT ROBUSTNESS_MIN_ACCURACY
    MCNEMAR_P_VALUE MEAN_CORRECT_CONFIDENCE MEAN_ERROR_CONFIDENCE LOW_MARGIN_COUNT PAIRED_NET_GAIN
    ACCEPTED_BRIER_SCORE ACCEPTED_BEST_EPOCH ACCEPTED_FINAL_LEARNING_RATE ACCEPTED_LOSS_REDUCTION
    ACCEPTED_NEGATIVE_LOG_LIKELIHOOD ACCEPTED_TRAIN_TEST_GAP ACCEPTED_TOP2_ACCURACY ACCEPTED_COHEN_KAPPA
    GRADIENT_CLIP_NORM LEARNING_RATE_DECAY SELECTIVE_HIGH_CONFIDENCE_COVERAGE
    SELECTIVE_HIGH_CONFIDENCE_ACCURACY TASK_IDENTIFIER TOP_CONFUSION_PAIR TRANSFORMER_CANDIDATE_ID
    TRANSFORMER_CANDIDATE_TITLE SECURITY_PROFILE_MODE SECURITY_NETWORK_POLICY SECURITY_INTEGRITY_ALGORITHM
    SECURITY_EXTERNAL_SIGNING SECURITY_FRAMEWORKS SECURITY_THREAT_COUNT SECURITY_CONTROL_COUNT SECURITY_ASSET_COUNT
    SECURITY_INVENTORY_INPUT_COUNT SECURITY_INVENTORY_ARTIFACT_COUNT SECURITY_ATTESTATION_STATUS
    SECURITY_ATTESTATION_CHECKED_COUNT SECURITY_ATTESTATION_MISSING_COUNT SECURITY_ATTESTATION_MISMATCH_COUNT
    SECURITY_CLAIM_SCOPE RESEARCH_OBJECT_ARTIFACT_COUNT RESEARCH_OBJECT_APPROVAL_STATE
    SCHEMA_MANIFEST_SCHEMA_COUNT ACCEPTED_TOP_RANK_FREQUENCY RANK_STABILITY_RUNNER_UP_ID
    PHASE_LEDGER_SETTLEMENT_PASS_COUNT FIGURE_QUALITY_FIGURE_COUNT FIGURE_QUALITY_VALID
    """.split()
)

STRICT_VALUE_TOKENS: frozenset[str] = frozenset(spec.name for spec in _TOKEN_SPECS if spec.strict_value)
