"""Bounded MNIST ML task package."""

from __future__ import annotations

from .task import (
    BaselineResult,
    CandidateResult,
    CandidateSpec,
    DatasetSummary,
    DiagnosticConfig,
    MLTaskResult,
    MNISTTaskConfig,
    RobustnessTransformSpec,
    TrainingConfig,
    accepted_error_examples,
    confusion_matrix,
    cross_entropy,
    deferred_candidate,
    evaluate_candidate,
    evaluate_nearest_centroid,
    evaluate_robustness,
    features_for_candidate,
    flatten_images,
    load_mnist_arrays,
    load_mnist_task_config,
    run_bounded_ml_task,
    select_accepted_candidate,
    softmax,
    summarize_dataset,
    tiny_patch_attention_features,
    train_mlp_classifier,
    train_softmax_classifier,
    write_confusion_matrix_csv,
    write_error_examples_json,
    write_training_history_csv,
)

__all__ = [
    "BaselineResult",
    "CandidateResult",
    "CandidateSpec",
    "DatasetSummary",
    "DiagnosticConfig",
    "MLTaskResult",
    "MNISTTaskConfig",
    "RobustnessTransformSpec",
    "TrainingConfig",
    "accepted_error_examples",
    "confusion_matrix",
    "cross_entropy",
    "deferred_candidate",
    "evaluate_candidate",
    "evaluate_nearest_centroid",
    "evaluate_robustness",
    "features_for_candidate",
    "flatten_images",
    "load_mnist_arrays",
    "load_mnist_task_config",
    "run_bounded_ml_task",
    "select_accepted_candidate",
    "softmax",
    "summarize_dataset",
    "tiny_patch_attention_features",
    "train_mlp_classifier",
    "train_softmax_classifier",
    "write_confusion_matrix_csv",
    "write_error_examples_json",
    "write_training_history_csv",
]
